event/urls.py
from django.urls import path
from .views import event,addEvent,addMember,deleteMember

app_name = "event"

urlpatterns = [
    path('',event, name='Event'),
    path('addEvent/',addEvent, name='addEvent'),
    path('addMember/<str:id>',addMember, name='addMember'),
    path('deleteMember/<str:id>',deleteMember, name='deleteMember')

]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='Home'),
    path('phortopholio/', views.phortopholio, name='Phortopholio'),
    path('story1/', views.story1, name='Story1'),
]

jadwal/urls.py
from django.urls import path
from .views import join, delete, detail

app_name = 'jadwal'

urlpatterns = [
    path('', join, name='Jadwal'),
    path('delete/<int:pk>', delete, name = 'delete'),
    path('detail/<int:pk>', detail, name='detail'),
]

story4/urls.py
from django.urls import path, include
from django.contrib import admin

app_name = 'story4'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('Jadwal/', include('jadwal.urls')),
    path('Event/', include('event.urls')),
]

event/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Member(models.Model):
    name = models.CharField(max_length=50)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    matkul = models.CharField(blank=False, max_length= 50)
    dosen = models.CharField(blank=False, max_length= 50)
    sks = models.IntegerField(blank=False)
    deskripsi = models.CharField(blank=False, max_length= 100, help_text ='jangan kepanjangan ya :)')
    semester = models.CharField(blank=False, max_length= 50)
    kelas = models.CharField(blank=False, max_length= 50, help_text ='contoh: Gasal 2019/2020')

event/forms.py
from django import forms
from .models import Event, Member

class CreateEvent(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name']

class CreateMember(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['name', 'event']

jadwal/forms.py
from django import forms

class SchedForm(forms.Form):
    matkul = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Mata Kuliah Kamu',
        'type' : 'text',
        'required' : True,
    }))
    dosen = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Dosen Kamu',
        'type' : 'text',
        'required' : True,
    }))
    sks = forms.IntegerField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah SKS Kamu',
        'type' : 'text',
        'required' : True,
    }))
    deskripsi = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi Mata Kuliah Kamu',
        'type' : 'text',
        'required' : True,
    }))
    semester = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Semester Kamu Sekarang',
        'type' : 'text',
        'required' : True,
    }))
    kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Di Kelas Mana Matkulnya',
        'type' : 'text',
        'required' : True,
    }))

event/views.py
from django.shortcuts import render, redirect
from .forms import CreateEvent, CreateMember
from .models import Event, Member

# Create your views here.
def event(request):
    event = Event.objects.all()
    member = Member.objects.all()
    return render(request, 'Event.html', {'event' : event, "member" : member})

def addEvent(request):
    if request.method == 'POST':
        form = CreateEvent(request.POST)
        if form.is_valid():
            form.save()
            return redirect('event:Event')
    return render(request, 'addEvent.html')

def addMember(request, id = 0):
    id = int(id)
    event = Event.objects.get(id=id)
    if request.method == 'POST':
        id = request.POST['eventId']
        name = request.POST['name']
        event = Event.objects.get(id=id)
        data = {'name' : name, 'event' : event}
        form = CreateMember(data=data)
        if form.is_valid():
            form.save()
            return redirect('event:Event')
    return render(request, 'addMember.html', {'event' : event})

def deleteMember(request, id):
    id = int(id)
    member = Member.objects.get(id=id)
    member.delete()
    return redirect('event:Event')

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'Home.html')

def phortopholio(request):
    return render(request, 'Phortopholio.html')

def story1(request):
    return render(request, 'Story1.html')

jadwal/views.py
from django.shortcuts import render, redirect
from .models import Jadwal
from .forms import SchedForm

# Create your views here.

def join(request):
    if request.method == 'POST':
        form = SchedForm(request.POST)
        if form.is_valid():
            jdwl = Jadwal()
            jdwl.matkul = form.cleaned_data['matkul']
            jdwl.dosen = form.cleaned_data['dosen']
            jdwl.sks = form.cleaned_data['sks']
            jdwl.deskripsi = form.cleaned_data['deskripsi']
            jdwl.semester = form.cleaned_data['semester']
            jdwl.kelas = form.cleaned_data['kelas']
            jdwl.save() 
        return redirect("/Jadwal")
    else:
        jdwl = Jadwal.objects.all()
        form = SchedForm()
        response = {'jadwal':jdwl, 'form': form}
        return render(request, 'Jadwal.html', response)

def delete(request, pk):
    # if request.method == 'GET':
    #     form = SchedForm(request.POST)
    #     jdwl = Jadwal()
    #     jdwl.objects.filter(pk = pk).delete()
    #     data = jdwl.objects.all()
    #     form = SchedForm()
    #     response = {
    #         "jadwal" : data,
    #         "form": form
    #     }
    #     return render(request, 'Jadwal.html', response)
    jdwl = Jadwal.objects.get(pk=pk)
    jdwl.delete()
    return redirect("/Jadwal")

def detail(request, pk):
    matkul = Jadwal.objects.get(pk=pk)
    response1= {
        "matkul" : matkul.matkul,
        "dosen" : matkul.dosen,
        "sks" : matkul.sks,
        "deskripsi" : matkul.deskripsi,
        "semester" : matkul.semester,
        "kelas" : matkul.kelas,
    }
    return render(request, 'Detail.html', response1)    

event/templates/Event.html
{% extends 'Layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'style-jadwal.css'%}">
{% endblock css %}

{% block content %}
<div class="main w-50 d-flex justify-content-center flex-column">
    <div class="tulisan d-flex justify-content-center mt-2" style="position: relative;">
        <span style="
            font-family: 'Montserrat', sans-serif;
            font-size: 20px;
            z-index: 1;
            display: block;
            font-weight: 900;
            font-size: 40px;
        ">
            EVENT KAMUUUUU!!!!!!
        </span>
    </div>
    <button type="button" class="btn btn-primary btn-lg my-2" href="{% url 'event:addEvent' %}">TAMBAH EVENT</button>
    <div class="table">
        {% for i in event %}
        <div class="card">
            <h5 class="card-header">{{ i.name }}</h5>
            <div class="card-body">
            <h5 class="card-title">ANGGOTA :</h5>
            <ul class="list-group">
            {% for j in member %}
                {% if j.event == i %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>{{j.name}}</span>
                        <a class="material-icons text-danger text-decoration-none" href="{% url 'event:deleteMember' j.id %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i>HAPUS ANGGOTA</button></a>
                    </li>
                {% endif %}
            {% endfor %}
            </ul>
            <button type="button" class="btn btn-info my-2" href="{% url 'event:addMember' id=i.id %}">TAMBAH ANGGOTA</button>
            </div>
        </div>
        {% endfor %}
    </div>
<br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endblock content %}

event/templates/addEvent.html
{% extends 'Layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'style-jadwal.css'%}">
{% endblock css %}

{% block content %}
<div class="main w-50 d-flex justify-content-center flex-column">
    <div class="header mt-4" style="
            font-family: 'Montserrat', sans-serif;
            font-style: normal;
            font-weight: 900;
            font-size: 28px;">
            <h1>Add Event</h1></div>
    <form action="" method="post" >
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Nama Event</label>
            <input type="text" class="form-control" name="name" id="name" aria-describedby="eventNameHelp">
        </div>
        <button type="submit" class="btn btn-primary">Tambah</button>
    </form>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endblock content %}

event/templates/addMember.html
{% extends 'Layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'style-jadwal.css'%}">
{% endblock css %}

{% block content %}
<div class="main w-50 d-flex justify-content-center flex-column">
    <div class="header mt-4" style="
            font-family: 'Montserrat', sans-serif;
            font-style: normal;
            font-weight: 900;
            font-size: 28px;">
            <h1>Add Member</h1></div>
    <form action="" method="post" >
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Name </label>
            <span>Event : {{event.name}}</span>
            <input type="text" class="form-control" name="name" id="name" aria-describedby="eventNameHelp">
            <input type="hidden" name="eventId" value="{{event.id}}">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endblock content %}

homepage/templates/Home.html
{% extends 'Layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'style-home.css'%}">
{% endblock css %}

{% block content %}
<div class="main d-flex justify-content-center flex-column" style="height: 84vh;">
    <div class="foto d-flex justify-content-center" data-aos="fade-down" data-aos-duration="1800">
        <div class="image">

        </div>
    </div>
    <a href="{% url 'homepage:Phortopholio'%}" style="font-weight: 900;" class="menu1 mt-3" data-aos="fade-down"
    data-aos-duration="1200">
        <span>PORTFOLIO</span>
    </a>
</div>
{% endblock content %}

homepage/templates/Layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
    {% endblock css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
    <link href="https://fonts.googleapis.com/css2?family=Bowlby+One+SC&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;700;900&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <title>Story3</title>
</head>
<body style="
    height: 100%;
">
    <nav class="navbar navbar-expand-lg navbar-light d-flex justify-content-center" style="background-color: #0168AA;">
        <!-- Navbar content -->
        <a class="navbar-brand mr-5" href="{% url 'homepage:Home' %}" style="
            font-family: 'Montserrat', sans-serif;
            font-style: normal;
            font-weight: 900;
            font-size: 28px;
            line-height: 22px;
            margin-right: 0px;
            
            color: #FFFFFF;
            ">HOME</a>
        <a class="navbar-brand mr-5" href="{% url 'homepage:Phortopholio' %}" style="
            font-family: 'Montserrat', sans-serif;
            font-style: normal;
            font-weight: 900;
            font-size: 28px;
            line-height: 22px;
            margin-right: 0px;
            
            color: #FFFFFF;
            ">PHORTOPHOLIO</a>
        <a class="navbar-brand mr-5" href="{% url 'homepage:Story1'%}" style="
            font-family: 'Montserrat', sans-serif;
            font-style: normal;
            font-weight: 900;
            font-size: 28px;
            line-height: 22px;
            margin-right: 0px;
            
            color: #FFFFFF;
            ">STORY1</a>
        <a class="navbar-brand mr-5" href="{% url 'jadwal:Jadwal'%}" style="
        font-family: 'Montserrat', sans-serif;
        font-style: normal;
        font-weight: 900;
        font-size: 28px;
        line-height: 22px;
        margin-right: 0px;
        
        color: #FFFFFF;
        ">JADWAL</a>
        <a class="navbar-brand " href="{% url 'event:Event'%}" style="
            font-family: 'Montserrat', sans-serif;
            font-style: normal;
            font-weight: 900;
            font-size: 28px;
            line-height: 22px;
            margin-right: 0px;
            
            color: #FFFFFF;
            ">EVENT</a>
    </nav>
    <div class="semuanya d-flex flex-row justify-content-center">
        <div class="kiri" style="
            width:27.5%;
            z-index: 100;
            background: white;
            display: block;
        ">

        </div>
        {% block content %}
        
        {% endblock content %}
        <div class="kanan" style="
        width:27.5%;
        z-index: 100;
        background: white;
    ">
    
        </div>
    </div>
    <div class="footer w-100">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #0168AA;">
            <!-- Navbar content -->
            <a class="navbar-brand " href="#">© Copyright by Said Nizamudin</a> 
            <div class="sosmed">
                <a href="https://api.whatsapp.com/send?phone=6282165201341"><img src="{% static 'wa.png'%}" alt="WhatsApp"></a>
                <a href="   https://www.instagram.com/saidnizam.udin/" class="mr-2"><img src="{% static 'igmantap.png'%}" alt="Instagram"></a>
                <a href="https://www.twitter.com/AmbulanceZig/" class="mr-1"><img src="{% static 'twittermantap.png'%}" alt="Twitter"></a>
            </div>
        </nav>
    </div>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>
</html>

homepage/templates/Phortopholio.html
{% extends 'Layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'style-phortopholio.css'%}">
{% endblock css %}

{% block content %}
<div class="main mb-5"style="
        z-index:-1;
    ">
        <div class="foto-atas d-flex justify-content-center mt-5 mb-5"  data-aos="fade-down" data-aos-duration="1200" >
            <div class="image">
    
            </div>
            <span>WELCOME TO MY WEBSITE.</span>
        </div>
        <div class="content" data-aos="fade-right" data-aos-duration="1800">
            <div class="circle1">
                
            </div>
            <div class="judul ml-3" id="judul1">
                <span>BIODATA</span>
            </div>
            <div class="isi ml-5 mt-2" id="biodata">
                <p>Nama saya Said Nizamudin dengan
                NPM 1906299124 dari angkatan Maung 2019. 
                Saya berkuliah di Fakultas Ilmu Komputer
                Universitas Indonesia dan mengambil  jurusan 
                Sistem Informasi. Saya orang yang suka berpetualang dan 
                memiliki  harapan dimana saya 
                dapat membantu orang banyak di kemudian  hari 
                dengan ilmu yang telah saya dapatkan :) </p>
            </div>
            <hr class="mt-5 mb-0">
        </div>
        <div class="content d-flex flex-column align-items-end mt-4"data-aos="fade-left" data-aos-duration="1400">
            <div class="circle2">
    
            </div>
            <div class="judul d-flex justify-content-end mr-1" id="judul2">
                <span>EDUCATION</span>
            </div>
            <div class="isi d-flex flex-column align-items-end mt-3 mr-5" id="education">
                <span><b>Universitas Indonesia</b></span> 
                <span>(2016-2019)</span> 
                <span><b>SMAN Modal Bangsa Aceh</b></span>
                <span>(2016-2019)</span> 
                <span><b>SMPN 19 Percontohan</b></span>
                <span>(2013-2019)</span> 
                <span><b>SDIT Nurul Ishlah Banda Aceh</b></span>
                <span>(2007-2013)</span> 
            </div>  
            <hr style="
            width: 100%;
            height: 1px;
            margin-bottom: 0px;
            " class="mt-5">
        </div>
        <div class="content mt-4 mb-5" data-aos="fade-right" data-aos-duration="1600">
            <div class="circle3">
    
            </div>
            <div class="judul ml-3" id="judul3">
                <span>EXPERIENCE</span>
            </div>
            <div class="isi ml-5 mt-2" id="experience">
                <ul>
                <li>Busidev PERAK 2020</li> 
                <li>Depor 2020 </li>
                <li>FnB Compfest 12 </li>
                <li>Kreatif PMB 2020 </li>
                <li>Pengajar Olimpiade Komputer 2020</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

homepage/templates/Story1.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylestory1.css'%}">

    <title>My Website</title>
  </head>
  <body>
    <div>
      <nav class="navbar navbar-expand-lg navbar-light bg-light mt-2 ">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav m-auto">
            <li class="nav-item ml-5">
              <a class="nav-link" href="#">MY BIODATA</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  
    <div class="col-sm">
          <div class="tengah">
            <div class="jumbotron">
              <h1 class="display-4 text-white">Welcome to My Website</h1>
              <hr class="my-4">
              <p class="text-white font-weight-bold lead" id="namaNPM">Terima Kasih... Sudah Berkunjung</p>
              <a class="btn btn-primary btn-lg" href="https://www.instagram.com/saidnizam.udin/" role="button">Visit My IG</a>
              <a class="btn btn-primary btn-lg ml-3" href="https://api.whatsapp.com/send?phone=6282165201341" role="button">Visit My WA</a>
              <a class="btn btn-primary btn-lg ml-3" href="https://www.twitter.com/AmbulanceZig/" role="button">Visit My Twitter</a>
            </div>

            <div class="card-item d-flex justify-content-center m-5">
              <div class="card d-inline-block mr-5 ml-5 " style="width: 18rem;">
                <img src="{% static 'Profil.JPG'%}" class="card-img-top" alt="Profile">
                <div class="card-body">
                  <h5 class="card-title">BIODATA</h5>
                  <hr>
                  <p class="card-text">Nama        : Said Nizamudin</p>
                  <p class="card-text">NPM         : 1906299124</p>
                  <p class="card-text">Angkatan    : Maung 2019</p>
                  <p class="card-text">Jurusan     : Sistem Informasi</p>
                  <p class="card-text">Universitas : Universitas Indonesia</p>
                  <p class="card-text">Hobi        : Ngoding, Basket, dan Travelling</p>
                </div>
              </div>
              <div class="card d-inline-block mr-5 ml-5" style="width: 18rem;">
                <img src="{% static 'UI.jpg'%}" class="card-img-top" alt="UI">
                <div class="card-body">
                  <h5 class="card-title">Riwayat Pendidikan</h5>
                  <hr>
                  <p class="card-text"><b>Universitas Indonesia</b><br><span>(2019-Sekarang)</span></p>
                  <p class="card-text"><b>SMAN Modal Bangsa Aceh</b><br><span>(2016-2019)</span></p>
                  <p class="card-text"><b>SMPN 19 Percontohan</b><br><span>(2013-2016)</span></p>
                  <p class="card-text"><b>SDIT Nurul Ishlah</b><br><span>(2007-2013)</span></p>
                
                </div>
              </div>
              <div class="card d-inline-block mr-5 ml-5" style="width: 18rem;">
                <img src="{% static 'Foto.JPG'%}" class="card-img-top" alt="Desciption">
                <div class="card-body">
                  <h5 class="card-title">About Me</h5>
                  <hr>
                  <p class="card-text">Saya adalah seorang anak yang memiliki rasa ingin tahu yang tinggi dan senang berpetualang :)</p>
                </div>
              </div>
            </div>
          </div>
        </div>

    <nav class="navbar navbar-light bg-dark mt-2">
      <p>&copy; Copyright by Said Nizamudin</p>
    </nav>

  </body>
</html> 

jadwal/templates/Detail.html
{% extends 'Layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'style-jadwal.css'%}">
{% endblock css %}

{% block content %}
<div class="main w-50 d-flex flex-column align-items-center">
    <div class="tulisan d-flex justify-content-center mt-2" style="position: relative;">
        <span style="
            font-family: 'Montserrat', sans-serif;
            font-size: 20px;
            z-index: 1;
            display: block;
            font-weight: 900;
            font-size: 40px;
        ">
            JADWALMU
        </span>
    </div>
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Dosen</th>
            <th scope="col">SKS</th>
            <th scope="col">Deskripsi</th>
            <th scope="col">Semester</th>
            <th scope="col">Kelas</th>
            </tr>
        </thead>
        <br>
        <tbody>
            <tr>
                <th scope="row">{{matkul}}</th>
                <td>{{dosen}}</td>
                <td>{{sks}}</td>
                <td>{{deskripsi}}</td>
                <td>{{semester}}</td>
                <td>{{kelas}}</td>
            </tr>
        </tbody>
    </table>     
    <a href="{% url 'jadwal:Jadwal'%}"> <button style="font-family: 'Montserrat', sans-serif;" 
        class="btn btn-primary align-items-center">BACK TO FORM JADWAL</button></a></td>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

jadwal/templates/Jadwal.html
{% extends 'Layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'style-jadwal.css'%}">
{% endblock css %}

{% block content %}
<div class="main w-50">
    <div class="tulisan d-flex justify-content-center mt-2" style="position: relative;">
        <span style="
            font-family: 'Montserrat', sans-serif;
            font-size: 20px;
            z-index: 1;
            display: block;
            font-weight: 900;
            font-size: 40px;
        ">
            ISI JADWAL YUK!!!
        </span>
    </div>
    <div class="form mt-4 mb-5">
        <form action='' method="POST">
            {% csrf_token %}
            {{ form }}
            <br>
            <div class="centre-items">
                <input type="submit" class="btn btn-primary" value="Add Schedule">
            </div>
        </form>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Mata Kuliah</th>
                </tr>
            </thead>
            <br>
            <tbody>
                {% for jadwal in jadwal %}
                <tr>
                    <th scope="row">{{jadwal.matkul}}</th>
                    <td><a href="{% url 'jadwal:delete' pk=jadwal.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i>Delete</button></a></td>
                    <td><a href="{% url 'jadwal:detail' pk=jadwal.pk %}"> <button class="btn btn-light">Detail</button></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
<br><br><br><br><br><br><br>
</div>
{% endblock content %}